apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    istio: ingress
  ports:
  - name: http2
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
